### PR TITLE
New tuj for TDI-47285 to cover TDI-46943_tFileInputExcel_Dynamic_not_cut_last_col

### PR DESCRIPTION
**Pull request by ovtkachenko**
Hello,

Please make a review of tuj according to https://jira.talendforge.org/browse/TDI-47285 (Create a tuj for Dynamic schema fail's with Excel). The parent ticket is https://jira.talendforge.org/browse/TDI-46943 (Dynamic schema fail's with Excel)

Thanks in advance.

### CODE REVIEW

**Comment by ovtkachenko** [comment]
The result of running tuj with Studio 801 in ttp dev.
image
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=6440&id_exec=70035

**Review by acatoire — CHANGES_REQUESTED** [review]
Created files are not unic (use PID)

**Comment by ovtkachenko** [comment]
Hello Axel, if we add pid to excel file it becomes unrecognizable. It would be great save excel files as is. Anyway I added pid to all files.
image
image

image

**Comment by acatoire** [comment]
You can add the PID before the .xls, so it will not "break" the file recognition

**Comment by ovtkachenko** [comment]
@acatoire please proceed with tuj review after changes.

**Comment by ovtkachenko** [comment]
The result of running tuj on the TTP Dev after changes:
image
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=6440&id_exec=70038

**Comment by acatoire** [comment]
LGTM

**Pull request merged**
