### PR TITLE
New tuj on TDI-42314 to cover TDI-46773_Create_tuj_for_tAmazonAuroraRow_component

### PR DESCRIPTION
**Pull request by ovtkachenko**
Hello,

Please make a review of tuj according to https://jira.talendforge.org/browse/TDI-46773 (Create a tuj for tAmazonAuroraRow component). The parent ticket is https://jira.talendforge.org/browse/TDI-42314 (tAmazonAuroraRow Component)

Thanks in advance.

### CODE REVIEW

**Comment by ovtkachenko** [comment]
The result of running of tujs is below:
image

**Review by acatoire — CHANGES_REQUESTED** [review]
Could you add assert on all tLogRow.
To be consistent between all jobs:
- Insert delete is checking all tLogRow
- others jobs only test one

**Review by acatoire — APPROVED** [review]

**Comment by acatoire** [comment]
LGTM

**Comment by ovtkachenko** [comment]
The result of running tujs on ttp dev:
image

**Pull request merged**
