### PR TITLE
Added TUJ TDI44268_tNeo4jv4_node_with_all_data_types_and_db_name

### PR DESCRIPTION
**Pull request by npanarina**

### CODE REVIEW

**Comment by npanarina** [comment]
Hi Inna Danylenko,
please review PR and check TUJs on Talend-Studio-20210122_1939-V7.4.1SNAPSHOT or newer.
TUJ was run successfully on TTP Dev (tuj/master/20210302_0900)

**Comment by idanylenko** [comment]
Please import the tuj from 7.3 studio version to make it available for maintenance/7.3 as well

**Review by idanylenko — CHANGES_REQUESTED** [review]
Please import the tuj from 7.3 studio version to make it available for maintenance/7.3 as well

**Comment by npanarina** [comment]
Updated TUJ was run successfully on TTP Dev (tuj/master/20210309_0711)

**Review by idanylenko — APPROVED** [review]
LGTM

**Pull request merged**
