### PR TITLE
Idanylenko/netsuite delete journal entry

### PR DESCRIPTION
**Pull request by idanylenko**
Hello,
please review two TUJs:

1. tuj\java\NetsuiteV2019\TDI45495_NetsuiteV2019_TransactionBody_custom_field_multiselect
2. tuj\java\Netsuite\TDI45601_tNetsuiteXX_TransactionBody_custom_field_multiselect

Since there are troubles last days with Jenkins builds on TTP Dev for both 7.3 and 7.4, I wasn't able to schedule a run there

Thanks in advance,
Inna

### CODE REVIEW

**Comment by fdesiles** [comment]
The following runs,  mentioned in https://github.com/Talend/tuj/pull/737 seem to have the results for both mentioned TUJs in this PR, is this correct ?
on maintenance/7.3: tuj/maintenance/7.3/20210426_2348
on master: tuj/master/20210426_2018

image

image

**Comment by idanylenko** [comment]
Yes

**Review by fdesiles — APPROVED** [review]
LGTM. Ready for merge. Ping me for PR port to maintenance/7.3 :)

**Comment by fdesiles** [comment]
Hello Inna,
the password from TDI45495_NetsuiteV2019_TransactionBody_custom_field_multiselect is missing the related context variable:
image

**Pull request merged**
