### PR TITLE
Update TDI37592_tFileInputExcel_Dynamic_DateFormat, replace ref files…

### PR DESCRIPTION
**Pull request by ovtkachenko**
Hello,

According to the research within https://jira.talendforge.org/browse/TDI-47203 the ref files have been replaced with new ones (generated by Studio).
Changes affected only master and maintenance/8.0 branches and are not affected the maintenance/7.3 (due to https://jira.talendforge.org/browse/TDI-46749 and fix version 801)

The result of tuj running with maintenance/8.0:
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=3487&id_exec=69774
image

### CODE REVIEW

**Review by fdesiles — CHANGES_REQUESTED** [review]
Hello @ovtkachenko,
In the associated ticket, if I understand well, only the ref file should have been modified to take into account the correction from https://jira.talendforge.org/browse/TDI-46749 .
However, in this PR, the whole job is marked as updated, while only the ref file should be in the commit.

If this is correct, could you please update the PR with only the update of ref file and confirm the execution is OK with original TUJ + new Ref File please ?

Thanks !

**Comment by ovtkachenko** [comment]
Hello @fdesiles ,
I tried to replace only ref files in the existing tuj but nothing to commit. 
image

**Comment by fdesiles** [comment]
You can try the following:

- Once you have saved your reference files somewhere outside your cloned repo (to apply it again afterwards)
- Revert your commit
- Replace the reference files with your new one you saved.
- If they are not detected by the commit, you can force it with: git add -f path/to/the/file

**Comment by ovtkachenko** [comment]
Hello Fabien,

The previous commit was reverted, the result of running tuj on ttp dev on the maintenance/8.0 branch is below:
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=3487&id_exec=69784
image

**Review by fdesiles — APPROVED** [review]
LGTM

**Pull request merged**
