### PR TITLE
Update TDI39298_tGoogleDriveCreate_Folder_Id, add pid and additional …

### PR DESCRIPTION
**Pull request by ovtkachenko**
https://jira.talendforge.org/browse/TDI-47064

Update tuj TDI39298_tGoogleDriveCreate_Folder_Id

Added pid to folders and additional steps with creating a folder

The results or running tuj are below (Success):
The results of running the tuj on v 7.3.1 (maintenance/7.3) https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69690
The results of running the tuj on v 8.0.1 (maintenance/8.0) https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69712

Could not run on Master due to
https://tal-rd209.talend.lan/colibri/execution_details.php?id=69708&build_last_lines=all
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[102] 2021-11-25 00:20:21 INFO  - [FATAL] Non-resolvable parent POM for org.talend.studio:tbd-studio-se:[unknown-version]: Could not find artifact org.talend.studio:parent-pom:pom:8.8.8-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 4, column 13

### CODE REVIEW

**Review by fdesiles — CHANGES_REQUESTED** [review]
Hello @ovtkachenko, there are a lot of files in this PR, not linked to TDI39298_tGoogleDriveCreate_Folder_Id. 
What is the reason ? Can we remove them to keep scope of the PR related to mentioned TUJ ?
Thanks.

**Comment by ovtkachenko** [comment]
Hello @fdesiles, 

Do you mean folders?

If I'm not mistaken the idea of this tuj is to check creation folder and subdirectories in that folder (check the tree of folders).

**Comment by fdesiles** [comment]
> 

Hello @ovtkachenko,
the PR have files which are not in scope of your modification, like, for example:
- /PostgreSql/*
- /Snowflake/*
- Other GoogleDrive TUJs
- ..

They don't seem to be linked to "TDI39298_tGoogleDriveCreate_Folder_Id" TUJ.

**Comment by ovtkachenko** [comment]
Hello @fdesiles , yes, I absolutely agree. Strange that PR contains them. I will update it.

**Review by fdesiles — CHANGES_REQUESTED** [review]
/LOCAL_PROJECT/ folder should no longer be in the TUJ folder:

tuj/java/Google/GoogleDrive/TDI39298_tGoogleDriveCreate_Folder_Id/LOCAL_PROJECT/

It leads to having the TUJ appear twice in Studio (see below) :)

image

**Review by fdesiles — CHANGES_REQUESTED** [review]
As discussed in Slack, cannot open TUJ in official Studio release due to it being modified with a Nightly version which don't seem to be compatible anymore (which would explain the failure also on TTP Dev in latest run).
Please update PR with a version modified with an official (7.2 or after) release.

**Comment by ovtkachenko** [comment]
Hello @fdesiles,

Thank you for your feedback, I rechecked this tuj with Talend-Studio-20211109_1610-V8.0.1 + Monthly Patch_20211217_R2021-12_v1-8.0.1 and it works good (you can see on screenshot). There is same error with Studio 7.3 on ttp dev:
java.lang.IllegalStateException: could not find process with name : TDI39298_tGoogleDriveCreate_Folder_Id
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69740
image

It looks very strange because tuj contains the process folder with files related to the tuj:
image

**Comment by ovtkachenko** [comment]
Result of running tuj on 801 https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69743
image

**Comment by ovtkachenko** [comment]
Result of running tuj on 731 https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69742
image
@fdesiles please take a look again.

**Comment by ovtkachenko** [comment]
7 files are present in PR:
image

**Review by fdesiles — DISMISSED** [review]

**Comment by fdesiles** [comment]
Thanks for the updates @ovtkachenko :)
		
		Few points from my side:
		I have no error while running the original TUJ locally. 
		If I run TDI39298_tGoogleDriveCreate_Folder_Id from maintenance/8.0, the test is passing also.
		See: https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69748 and https://tal-rd209.talend.lan/jenkins/job/launch-tuj/11131/parameters/
		
		If I look at the tickets for the update:
		- I can't reproduce bug mentioned in https://jira.talendforge.org/browse/TDI-46966 (the folder in question is not in the TUJ on Master, it seems the one executed in the ticket is already a modified TUJ).
		- I see that it is in Logic error on TTP Prod, however, the parent ticket for TDI39298_tGoogleDriveCreate_Folder_Id is linked to parallel execution (https://jira.talendforge.org/browse/TDI-46890). The proposal for correction doesn't seem to match with what is done in this PR, as folder listing is still executed at the end as mentioned in the description:
		> The error is caused by the parallel running of TTP jobs. But we could try to fix the problem from the job design, not to list all created google driver folders at the last step of jobs (illustrated by the attached image, tGoogleDrive_LogicErr_ListFolders.png).
		
		My question:
		As for me, local execution is green with master or with your PR, I thought we'd have the same logic results if we merge this update as the root cause mentioned in https://jira.talendforge.org/browse/TDI-46890 is not corrected.
		But the modification of the folder implies that fewer elements are fetched with the last tGoogleDriveList and could be the solution.
		Are we sure that the proposal for correction fix the initial https://jira.talendforge.org/browse/TDI-46890 as the run is currently green whether I run the original TUJ of the modified one ?

**Comment by ovtkachenko** [comment]
Hello @fdesiles, 

Please take a look at PR after modification of tuj.
7.3 https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69750
8.0 https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69751

Thanks in advance.

**Review by fdesiles — APPROVED** [review]
Thanks for the updates.
LGTM

**Pull request merged**
