### PR TITLE
Idanylenko/netsuite delete custom transaction

### PR DESCRIPTION
**Pull request by idanylenko**
Hello,
please review two TUJs:

- java\NetsuiteV2019\TDI45495_NetsuiteV2019_TransactionBody_custom_field_multiselect
- java\Netsuite\TDI45601_tNetsuiteXX_TransactionBody_custom_field_multiselect

Successful TTP-Dev runs are:
on maintenance/7.3: tuj/maintenance/7.3/20210426_2348
on master: tuj/master/20210426_2018

### CODE REVIEW

**Comment by fdesiles** [comment]
Hello @idanylenko,
I can't find the mentioned TUJs on the related branch. Maybe a bad copy/past from https://github.com/Talend/tuj/pull/738 ?

**Comment by idanylenko** [comment]
Hello Fabien!
You are right, it's a mistake, sorry. Correct names of TUJs are:

1. java\NetsuiteV2019\TDI45898_tNetsuiteV2019Output_delete_custom_transaction
2. java\Netsuite\TDI45899_tNetsuiteOutput_delete_custom_transaction

**Comment by fdesiles** [comment]
Waiting on following runs as the ones mentioned in this ticket refers to https://github.com/Talend/tuj/pull/738 and not this branch:

- #10783 for maintenance/7.3
- #10784 for master

**Comment by fdesiles** [comment]
Hello Inna,
the password from TDI45495_NetsuiteV2019_TransactionBody_custom_field_multiselect is missing the related context variable:
image

**Comment by fdesiles** [comment]
Other TUJ OK.
image

Waiting for correction on TDI45495_NetsuiteV2019_TransactionBody_custom_field_multiselect as mentioned above.

**Comment by idanylenko** [comment]
Thanks, Fabien!
I've fixed java\NetsuiteV2019\TDI45898_tNetsuiteV2019Output_delete_custom_transaction and scheduled new TTP Dev runs to check it:
#10787
#10788

**Comment by idanylenko** [comment]
run on master is successful for TDI45898_tNetsuiteV2019Output_delete_custom_transaction (tuj/master/20210527_0629)
run on 7.3 is still in progress - can be seen tomorrow morning

**Comment by idanylenko** [comment]
TDI45898_tNetsuiteV2019Output_delete_custom_transaction is also OK on 7.3 (tuj/maintenance/7.3/20210527_0927)

**Review by fdesiles — APPROVED** [review]
LGTM

**Pull request merged**
