### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fdesiles**
Add info on which version of Studio to use when creating TUJ.

### CODE REVIEW

**Review by ypiel-talend — APPROVED** [review]
LGTM

**Comment by ovtkachenko** [comment]
Hello @fdesiles,

Some notes from me are below:
1 - how do we know when feature started to be available, where can we check it? 
2 - does released version mean Monthly Patch?
3 - how do we act with updating the tuj, same? Should we add changes to existing tuj based on the oldest Studio or 7.3 is ok?
4 - should we change the design of existing tuj if it does not cover the requirements of standard template?

It would be great to add these use cases to README.md file as well.

Thanks in advance.

**Comment by fdesiles** [comment]
Hello @ovtkachenko,

1. The fix version of the ticket is the reference. As TUJ have the ticket number in it's name, it can be retrieved.
-> This point is covered by the readme: (JIRA_ID)_(component_name)_(use_case)

2. Yes it is. If the feature is available starting on October release of 7.3 for example, TUJ should be created using 7.3 + October monthly. Before it won't work and using a later version (for example 8) won't allow to run the TUJ on 7.3 November and December (therefore if a backport is required on 7.3, the TUJ won't be able to check regression on this feature for 7.3).
-> Covered this point in the use case example:
Case 1: Feature is available starting from 7.3.1-R2021-10
Expected:
Create TUJ on Official Released 7.3.1-R2021-10

3. As mentioned in Slack today, we have an agreement to not modify existing TUJ, unless validated with Pierre. When we agree to modify one, we should use the oldest supported Studio version for the feature. If another update on the component is required in the oldest supported version for the feature, we want to be able to run the regression checks.
-> Covered this point on use case example:
Version:
Use version of the feature implementation to create automated tests.
What to avoid: Using a later version (ex: 8.0.1+) won't allow to run TUJ on previous ones.

4. Not sure to understand. Do you mean update existing TUJ if they don't follow the template? If that's the case, the answer is no. The template is for new TUJs. It enters under the agreement to not modify existing TUJs :)

**Review by ovtkachenko — APPROVED** [review]
Hello @fdesiles,
there are some tujs created on versions that have been retired, so probably we should take last available released version of Studio.
LGTM

**Pull request merged**
