### PR TITLE
Update 44917 tGSx TUJs to not use obsolete auth

### PR DESCRIPTION
**Pull request by fdesiles**
HMAC Auth is obsolete. Update TDI-44917 tGSx TUJs to use Service Account Auth.
Update done with Studio 8 as the obsolete auth only comes in Studio 8 and over.

tGSxx will now fail instead of being in Codegen error as long as https://jira.talendforge.org/browse/TDI-47006 is not corrected.
tGSPut is not impacted by this bug so is now working as expected: 
- https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5942&id_exec=69736

List of TUJs impacted by the modification (from Google family):
1. TDI44917_tGSBucketCreate_ERROR_MESSAGE
2. TDI44917_tGSBucketDelete_ERROR_MESSAGE
3. TDI44917_tGSBucketExist_ERROR_MESSAGE
4. TDI44917_tGSCopy_ERROR_MESSAGE
5. TDI44917_tGSDelete_ERROR_MESSAGE
6. TDI44917_tGSGet_ERROR_MESSAGE
7. TDI44917_tGSList_ERROR_MESSAGE
8. TDI44917_tGSPut_ERROR_MESSAGE

image

### CODE REVIEW

**Comment by ovtkachenko** [comment]
Hello @fdesiles,

Thank you for your feedback, I rechecked this tuj with Talend-Studio-20211109_1610-V8.0.1 + Monthly Patch_20211217_R2021-12_v1-8.0.1 and it works good (you can see on screenshot). There is same error with Studio 7.3 on ttp dev:
java.lang.IllegalStateException: could not find process with name : TDI39298_tGoogleDriveCreate_Folder_Id
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5407&id_exec=69740
image

**Comment by ovtkachenko** [comment]
It looks very strange because tuj contains the process folder with files related to the tuj:
image
image

**Comment by ovtkachenko** [comment]
Hello @fdesiles,

There are some notes after review:
1 - for TDI44917_tGSBucketCreate_ERROR_MESSAGE: I didn't catch assert with Studio v801 just: Exception in component tGSBucketCreate_1 (TDI44917_tGSBucketCreate_ERROR_MESSAGE) error "message" : "You already own this bucket. Please select another name.", and job fail and die;
image

2 - for TDI44917_tGSBucketDelete_ERROR_MESSAGE: I didn't catch assert with Studio v801 just:
Exception in component tGSBucketDelete_1 (TDI44917_tGSBucketDelete_ERROR_MESSAGE)
[FATAL] 19:38:53 finalcheck.tdi44917_tgsbucketdelete_error_message_0_1.TDI44917_tGSBucketDelete_ERROR_MESSAGE- tGSBucketDelete_1 Can't find bucket with name: 'nonexistingbucketdummy44917'.
java.lang.IllegalArgumentException: Can't find bucket with name: 'nonexistingbucketdummy44917'. and job fail and die;
image

3 - for DI44917_tGSBucketExist_ERROR_MESSAGE: I didn't catch assert with Studio v801 just:  Exception in component tGSBucketExist_1 (TDI44917_tGSBucketExist_ERROR_MESSAGE)
com.google.cloud.storage.StorageException:  Bucket names must be at least 3 characters in length, got 2: '42' and job fail and die;
image

4 - for TDI44917_tGSCopy_ERROR_MESSAGE: I didn't catch assert with Studio v801 just: Exception in component tGSCopy_1 (TDI44917_tGSCopy_ERROR_MESSAGE)
java.lang.NullPointerException and job fail and die;
image

5 - for TDI44917_tGSDelete_ERROR_MESSAGE: I didn't catch assert with Studio v801 just: Exception in component tGSDelete_1 (TDI44917_tGSDelete_ERROR_MESSAGE)
java.lang.NullPointerException and job fail and die;
image

6 - for TDI44917_tGSGet_ERROR_MESSAGE: I didn't catch assert with Studio v801 just: Exception in component tGSGet_1 (TDI44917_tGSGet_ERROR_MESSAGE) 
java.lang.NullPointerException and job fail and die;
image

7 - for TDI44917_tGSList_ERROR_MESSAGE: I didn't catch assert with Studio v801 just: Exception in component tGSList_1 (TDI44917_tGSList_ERROR_MESSAGE)
java.lang.NullPointerException and job fail and die;
image
Is it expected? or wrong configuration of tujs? or lack of knowledge about Die on Error option?
8 - TDI44917_tGSPut_ERROR_MESSAGE - it's ok
image
 I look at this description of Die on error option:
image

**Comment by fdesiles** [comment]
Hello @ovtkachenko,

Yes, those results are expected as mentioned in the original post of the PR:

> tGSxx will now fail instead of being in Codegen error as long as https://jira.talendforge.org/browse/TDI-47006 is not corrected.

> tGSPut is not impacted by this bug so is now working as expected

A bit more context:

- Previously, those TUJs were using a deprecated Auth method. Using this method, the Die on Error was working as expected.
- With Studio 8, the auth method became obsolete, so all tGSxx were in CodeGen error, we had to update the auth method.
- Changing the Auth method, I found that there was a bug for most of tGSxx components, which I raised in https://jira.talendforge.org/browse/TDI-47006
- tGSPut is not impacted by this bug, so the update is now working and TUJ is green
- For all other tGSxx components, the bug is present, therefore the TUJs can't work and should fail as expected (but not with a codegen error).

Please let me know if more context is needed :)

**Comment by ovtkachenko** [comment]
Hello @fdesiles,
how do we understand that the tuj works as expected if no asserts shown it? They will always fail on the ttp-dev and it's ok, just no Codegen error, yes?

**Comment by fdesiles** [comment]
Hello @ovtkachenko,
Yes, that's right. The TUJ is failing without assert because what is inside it should not stop the Job from being executed.
Here it 'dies on error' where it should not.
We want to avoid the codegen however and that was achieved.

**Review by ovtkachenko — APPROVED** [review]
LGTM

**Pull request merged**
