### PR TITLE
Add new TUJ on tFTPFileList for duplicate of local variable

### PR DESCRIPTION
**Pull request by fdesiles**
Port to 7.4.1 of following PR:
https://github.com/Talend/tuj/pull/741

For 7.3.1 results:
TUJ result on TTP Dev in success:
https://tal-rd209.talend.lan/colibri/job_details.php?id_job=5973&id_exec=69411

Related ticket https://jira.talendforge.org/browse/TDI-46060

Also been run locally with success (on both 7.3.1 and 7.4.1)

### CODE REVIEW

**Review by vmurenko — COMMENTED** [review]
I think here it should be like - 'Create table if does not exist' or not?
Captweweure

**Comment by ovtkachenko** [comment]
Hello,

my notes are following:

1) we could add tFixedFlowInput and tFileOutputDelimited to define a File Name context.data_output_dir + "/" + jobName + "/out.csv" where we can put file mask files
2) we could add tFTPConnection component and fill the credentials in one place;
3) we could add files - "TDI46060.csv", "TDI46060d.csv" to tFTPFileList_1 and  tFTPFileList_2;
4) we should add tPostjob and tFTPDelete_1 at the end of tuj and put files "TDI46060.csv", "TDI46060d.csv" inside of tFTPDelete_1
image
image

**Comment by fdesiles** [comment]
> I think here it should be like - 'Create table if does not exist' or not?
> Captweweure

The Colibri component is part of a template for TUJs, so we should not modify it.
Thanks for the remark, I'll add those info in the wiki 👍

**Comment by fdesiles** [comment]
Hello @ovtkachenko,
Concerning https://github.com/Talend/tuj/pull/742#issuecomment-895114877

We could indeed, but we try to keep TUJs as simple and little as possible.
Here, the ticket is about a compilation error we introduced in a recent version of tFTPFileList when using several times the same component in the job.
As we are using a FTP target which is already used, we know there are some files on it. So the simplest way is to use what is already available so that we have a limited scope on this TUJ.

Your proposal is totally valid. Just a warning thought, in case of problem on file masking, tFTPConnection or some other points not linked to tFTPFileList, debugging might be less straightforward.

Thanks for the feedback ! It will help to update the guidelines.

**Comment by ovtkachenko** [comment]
LGTM

**Review by ovtkachenko — APPROVED** [review]
LGTM

**Pull request merged**
