### PR TITLE
TDI44268 with Neo4jv4 TUJs, TDI45050 with UNWIND queries for tNeo4jv4…

### PR DESCRIPTION
**Pull request by npanarina**
…Output

Please check TUJs on Talend Studio with monthly patch 7.3.1-R2020-11 or newer

### CODE REVIEW

**Comment by idanylenko** [comment]
Hello Nataliia,
Here is a summary of what I suggest to improve:
1. (Microbe one). In CRUD tuj you have a subjob named "Create from Input component". It can be understood like "create from from tNeo4jv4Input component". I think it's better to name it like "Create from Fixed Input"
2. It's better to use more self-explanatory names of variables you add to GlobalMap. You used query1, query2, ... evetrywhere, but it's difficult to read the tuj when there are a lot of such "query". You see it in the component where its used - and then to find out what it's doing - you need to switch back to tJava to see the full query text. What if to name them like "query_createNode", "query_deleteNode" etc instead of simple query1, query2? I had to tell it to you earlier, when we were discussing your TUJs, my bad. But there is still a chance to improve :)
3. The rule "Export tuj from root of studio, no folders" - violated
4. No need for `System.out.println(query1);` in tJava. I showed it to you for debug purpose only, when we were developing TUJ - now it's redundant and can be deleted
5. We use `On Subjob OK` trigger to connect subjobs. `On Component OK` is rarely used (mostly in cases when `On Subjob OK` is not applicable). Please check, some of your TUJs use `On Component OK` 
6. You can use "Table" checkbox for tLogRow: in this case output will be more beautiful and readable (it will form a table and include column names to it besides the data)
7. TDI44268_tNeo4jv4_retrieve_null_value doesn't pass on the first try
Please reach out to me for discussions if needed

**Comment by npanarina** [comment]
Hello Inna,
Thank you for your suggestions.
1. Done, the subjob name was changed to "Create the second node from FixedFlowInput".
2. Done, query names were clarified in all TUJ.
3. Fixed.
4. Done, System.out.println(query1) removed from tJava component in 4 TUJs.
5. Done, "On Subjob OK" trigger was used in all TUJs.
6. Done, "Table" checkbox was checked for tLogRow component in all TUJs and .settings folder 
7. Done, query was fixed.
Please, review these TUJs again.

**Review by idanylenko — APPROVED** [review]
Great job!

**Comment by npanarina** [comment]
Thank you for your advices, Inna!

**Pull request merged**
